-- 020_add_currency_columns.sql v0.1.0 (2025-08-19)
ALTER TABLE accounts ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'EUR';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'EUR';
ALTER TABLE positions ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'EUR';
ALTER TABLE executions ADD COLUMN IF NOT EXISTS currency VARCHAR(3) DEFAULT 'EUR';
