-- 021_add_fee_tax_columns.sql v0.1.0 (2025-08-20)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fee NUMERIC DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax NUMERIC DEFAULT 0;
ALTER TABLE executions ADD COLUMN IF NOT EXISTS fee NUMERIC DEFAULT 0;
ALTER TABLE executions ADD COLUMN IF NOT EXISTS tax NUMERIC DEFAULT 0;
