# ci.yml v0.1.0
name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: python -m compileall .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        service: [api-gateway, orchestrator, data-ingestion, strategy-engine, risk-engine, execution-engine, backtester, ui]
    steps:
      - uses: actions/checkout@v4
      - name: Build service image
        run: |
          if [ -f "${{ matrix.service }}/Dockerfile" ]; then
            docker build -t ${{ matrix.service }} ${{ matrix.service }}
          else
            echo "No Dockerfile for ${{ matrix.service }}, skipping."
          fi
